analysis:
  alpha: 0.99
  n_simulations: 100_000
  historical_sample_period: 180
  thresholds:
    periods:
      liquidation: 21
      premium_redeem: 14
      safe_mint: 7
debt:
  btc: "bitcoin"
  usd: "dollar"
collateral:
  polkadot:
    dot: 
      name: "polkadot"
      risk_adjustment:
        liquidity_adjustment: 0
        depeg_adjustment: 0
      supply_cap: 2_450_000
    usdt:
      name: "tether"
      risk_adjustment:
        liquidity_adjustment:
        depeg_adjustment: 0.08
      supply_cap: 2_000_000
    qusdt:
      name: "tether"
      risk_adjustment:
        liquidity_adjustment: 0.04
        depeg_adjustment: 0.08
      supply_cap: 1_752_709
    usdc:
      name: "usd-coin"
      risk_adjustment:
        liquidity_adjustment:
        depeg_adjustment: 0.13
      supply_cap: 2_000_000
    qusdc:
      name: "usd-coin"
      risk_adjustment:
        liquidity_adjustment: 0.04
        depeg_adjustment: 0.13
      supply_cap: 1_629_812
    vdot: 
      name: "voucher-dot"
      proxy:
        dot: "polkadot"
      risk_adjustment:
        liquidity_adjustment: 0.02
        depeg_adjustment:
      supply_cap: 1_500_000
  kusama:
    kbtc:
      name: "kintsugi-btc"
      proxy:
        btc: "bitcoin"
      risk_adjustment:
        liquidity_adjustment: 0.05
        depeg_adjustment: 0
      supply_cap: 20
    ksm: 
      name: "kusama"
      risk_adjustment:
        liquidity_adjustment: 
        depeg_adjustment:
      supply_cap: 100_000
    vksm: 
      name: "bifrost-ksm"
      proxy:
        ksm: "kusama"
      risk_adjustment: 
        liquidity_adjustment: 0.083
        depeg_adjustment: 0.07 # depeg of lido ETH
      supply_cap: 2_000
    usdt:
      name: "tether"
      proxy:
        usd: "dollar"
      risk_adjustment:
        liquidity_adjustment: 0.05
        depeg_adjustment: 0.086
      supply_cap: 800_000



