analysis:
  alpha: 0.99
  n_simulations: 20_000
  historical_sample_period: 365
  thresholds:
    periods:
      liquidation: 7
      premium_redeem: 14
      safe_mint: 21
collateral:
  dot: 
    name: "polkadot"
    risk_adjustment:
      liquidity_adjustment: 
      depeg_adjustment: 
  ksm: 
    name: "kusama"
    risk_adjustment:
      liquidity_adjustment: 
      depeg_adjustment: 
  stksm:
    name:  "lido-on-kusama"
    proxy:
      ksm: "kusama"
    risk_adjustment:
      liquidity_adjustment: 0.07
      depeg_adjustment: 0.07
  lksm: 
    name: "liquid-ksm"
    risk_adjustment: 
      liquidity_adjustment: 0.03
      depeg_adjustment: 0.07
  ausd: 
    name: "acala-dollar-acala"
    risk_adjustment:
      liquidity_adjustment: 
      depeg_adjustment: 0.99
  ausd:
    name: "acala-dollar"
    risk_adjustment:
      liquidity_adjustment: 
      depeg_adjustment: 0.99

