analysis:
  alpha: 0.99
  n_simulations: 100_000
  historical_sample_period: 365
  thresholds:
    periods:
      liquidation: 7
      premium_redeem: 14
      safe_mint: 21
debt:
  btc: "bitcoin"
  usd: "dollar"
collateral:
  polkadot:
    ibtc:
      name: "interlay-btc"
      proxy:
        btc: "bitcoin"
      risk_adjustment:
        liquidity_adjustment:
        depeg_adjustment: 0
      supply_cap: 30
    dot: 
      name: "polkadot"
      risk_adjustment:
        liquidity_adjustment: 
        depeg_adjustment: 
      supply_cap:
    usdt:
      name: "tether"
      risk_adjustment:
        liquidity_adjustment: 0.002
        depeg_adjustment: 0.08
      supply_cap: 200_000
  kusama:
    kbtc:
      name: "kintsugi-btc"
      proxy:
        btc: "bitcoin"
      risk_adjustment:
        liquidity_adjustment: 0
        depeg_adjustment: 0
      supply_cap: 20
    ksm: 
      name: "kusama"
      risk_adjustment:
        liquidity_adjustment: 
        depeg_adjustment:
      supply_cap: 100_000
    lksm: 
      name: "liquid-ksm"
      proxy:
        ksm: "kusama"
      risk_adjustment: 
        liquidity_adjustment: 0.06
        depeg_adjustment: 0.07 # depeg of lido ETH
      supply_cap: 55_000
    vksm: 
      name: "bifrost-ksm"
      proxy:
        ksm: "kusama"
      risk_adjustment: 
        liquidity_adjustment: 0.04
        depeg_adjustment: 0.07 # depeg of lido ETH
      supply_cap: 500
    usdt:
      name: "tether"
      proxy:
        usd: "dollar"
      risk_adjustment:
        liquidity_adjustment: 0.05
        depeg_adjustment: 0.086
      supply_cap: 800_000



